"""empty message

Revision ID: 0003d2cc7e9e
Revises: 
Create Date: 2025-10-11 10:30:32.163839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003d2cc7e9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alt', sa.String(length=255), nullable=True))
        batch_op.drop_column('custumers_opinion')
        batch_op.add_column(sa.Column('custumers_opinion', sa.Float(), nullable=True))
        batch_op.drop_column('saving_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saving_percentage', sa.INTEGER(), nullable=True))
        batch_op.alter_column(
            'custumers_opinion',
            existing_type=sa.Float(),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True
        )
        batch_op.drop_column('alt')
        batch_op.drop_column('image')

    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
