"""empty message

Revision ID: d778e6cdb68b
Revises: 0003d2cc7e9e
Create Date: 2025-10-11 11:34:28.533317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd778e6cdb68b'
down_revision = '0003d2cc7e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customers_opinion', sa.Float(), nullable=True))
        batch_op.drop_column('custumers_opinion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custumers_opinion', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('customers_opinion')

    # ### end Alembic commands ###
